export const APPS = Object.freeze([
  {code:'VENDAS',name:'Forte Vendas',category:'Comercial',description:'Balcão, clientes, orçamentos e estoque operacional.',url:'https://forte-vendas.onrender.com',accent:'#c82333',tint:'#fff0f2',icon:'/central/icons/vendas-aprovado-320.png'},
  {code:'FINANCEIRO',name:'Forte Financeiro',category:'Financeiro',description:'Contas a pagar e receber, caixa e conciliação bancária.',url:'https://forte-financeiro.onrender.com',accent:'#147050',tint:'#eaf7f0',icon:'/central/icons/financeiro-aprovado-320.png'},
  {code:'FISCAL',name:'Forte Fiscal',category:'Fiscal',description:'Documentos fiscais, XML, SPED e estoque por CNPJ.',url:'https://forte-fiscal.onrender.com',accent:'#1d64a7',tint:'#edf4fc',icon:'/central/icons/fiscal-aprovado-320.png'},
  {code:'FRETE',name:'Forte Frete',category:'Transporte',description:'Motoristas, veículos, documentos e acompanhamento de viagens.',url:'https://forte-frete.onrender.com',accent:'#a52c38',tint:'#fff1f3',icon:'/central/icons/frete-aprovado-320.png'},
  {code:'VENDA_EXTERNA',name:'Venda Externa',category:'Comercial',description:'Clientes, obras, propostas e acompanhamento das vendas.',url:'https://forte-venda-externa.onrender.com',accent:'#49649e',tint:'#f0f3fc',icon:'/central/icons/venda-externa-aprovado-320.png'},
  {code:'CARGA_DIRETA',name:'Carga Direta',category:'Logística',description:'Pedidos ao fornecedor, cargas diretas e pallets.',url:'https://forte-carga-direta.onrender.com',accent:'#2a716e',tint:'#edf7f6',icon:'/central/icons/carga-direta-aprovado-320.png'},
  {code:'PATIO',name:'Operador de Pátio',category:'Estoque',description:'Contagem física, reservas e conferência para fechamento do caixa.',url:'https://forte-operador-patio.onrender.com',accent:'#a2670a',tint:'#fff6e7',icon:'/central/icons/patio-aprovado-320.png'},
  {code:'SITE',name:'Site Forte Atacarejo',category:'Institucional',description:'Catálogo por marca, produtos e solicitações de orçamento.',url:'https://site-forte-atacarejo.onrender.com',accent:'#082b50',tint:'#edf2f8',icon:'/central/icons/site-aprovado-320.png'}
]);
